name: Deploy Multiple Function Apps

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-path: ['SEP4-AlarmService', 'SEP4-ClockService']
        app-name: ['Backend/AAlarmService', 'Backend/AClockService']
        publish-profile: [${{ secrets.AZURE_PUBLISH_PROFILE_ALARM_SERVICE }}, ${{ secrets.AZURE_PUBLISH_PROFILE_CLOCK_SERVICE }}]

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet 8.0.x Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: |
          cd ${{ matrix.app-path }}
          dotnet restore

      - name: Build
        run: |
          cd ${{ matrix.app-path }}
          dotnet build --configuration Release --no-restore

      - name: Publish
        run: |
          cd ${{ matrix.app-path }}
          dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ matrix.app-name }}
          package: './${{ matrix.app-path }}/publish'
          publish-profile: ${{ matrix.publish-profile }}
