name: Azure Deployment

on:
  push:
    branches:
      - CICD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t docker-compose.yml .

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <your-azure-container-registry-name>
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker Image to Azure Container Registry
        run: docker push your_image_name

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: sep4
          multi-container-config-type: "compose"
